apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: simpleapp
  ports:
  - protocol: TCP
    port: 80         # The port the service listens on inside the cluster
    targetPort: 5000 # The port your Flask app runs on inside the container
